name: Build & Publish container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Prepare Docker build tree
      run: |
        mkdir target/docker
        cp src/main/docker/Dockerfile target/docker/.
        cp src/main/shell/startapp.sh target/docker/.
        cp src/run/resources/configuration.properties target/docker/.
    - name: Build Docker container
      uses: azure/docker-login@v1
      with:
        login-server: zlarifhoacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - run: |
        cd target/docker && docker build -t zlarifhoacr.azurecr.io/kafkatests:${{ github.sha }} .

    # - uses: azure/docker-login@v1
    #     with:
    #       login-server: yourACRname.azurecr.io
    #       username: ${{ secrets.ACR_USERNAME }}
    #       password: ${{ secrets.ACR_PASSWORD }}