name: Build & Publish container

on:
  push:
    branches: [ main, DOCKHUB ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Prepare Docker build tree
      run: |
        cp src/main/docker/* target/.
        cp src/run/conf/configuration.properties target/.

    - name: Build Docker container
      uses: azure/docker-login@v1
      with:
        login-server: zlarifhoacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        export RELEASE_TAG=`cat RELEASE`
        cd target
        docker build -t zlarifhoacr.azurecr.io/kafkatests:"$RELEASE_TAG" .
        docker push zlarifhoacr.azurecr.io/kafkatests:"$RELEASE_TAG"

    #${{ github.sha }} 
